### PR TITLE
Ceph: build master with charmcraft3

### PR DESCRIPTION
**Pull request by sabaini**
Add separate recipes for jammy-caracal

### CODE REVIEW

**Review by UtkarshBhatthere — COMMENTED** [review]
LGTM but i didn't see an entry for ceph-osd charm, is it intentional ??

**Comment by sabaini** [comment]
> LGTM but i didn't see an entry for ceph-osd charm, is it intentional ??

There is an entry for ceph-osd, it should get its branch config from the default so no change required there.

**Review by UtkarshBhatthere — APPROVED** [review]
Let's ship it!

**Comment by sabaini** [comment]
Closing, need to change branch naming

**Pull request closed without merging**
